version: '3.8'
services:
  spoolman:
    image: olyforge3d/spoolman:test
    environment:
      - SPOOLMAN_LOGGING_LEVEL=INFO
      - TZ=Europe/Stockholm
  tester:
    image: olyforge3d/spoolman-tester:latest
    volumes:
      - ./tests:/tester/tests
    environment:
      - DB_TYPE=sqlite
    depends_on:
      - spoolman
